# addresspool.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: custom-addresspool
  namespace: metallb-system
spec: 
  addresses:
  - 172.20.88.65-172.20.88.68

# 172.20.88.65    reports51
# 172.20.88.66    reports52
# 172.20.88.67    reports53
# 172.20.88.68    reports54