apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-hello-world-web-service
  #namespace: default
  annotations:
    # https://github.com/ubuntu/microk8s/issues/2035
    kubernetes.io/ingress.class: public # was 'nginx' before microk8s 1.20
    nginx.ingress.kubernetes.io/ssl-redirect: "false" 
spec:
  tls:
  - hosts: 
    - alb-ubu
    # secret must be in same namespace
    secretName: tls-credential
  rules:
  - host: alb-ubu
    http:
      paths:
      - pathType: Prefix #Exact
        path: "/myhello/"
        backend:
          service:
            name: golang-hello-world-web-service
            port:
              number: 8080

