---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-manager-certificate
spec:
  secretName: mongodb-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: "*.reports-mongodb-svc.mongo.svc.cluster.local"
  dnsNames:
  - "*.reports-mongodb-svc.mongo.svc.cluster.local"
  - reports51:30351
  - reports52:30352
  - reports53:30353
  - reports54:30354
