#!/bin/bash
# export ACRNAME=mobexcr
# export AKSCLUSTER=reports-aks
# export RESOURCEGROUP=reports
# export NODERESOURCEGROUP=MC_reports_reports-aks_centralus
printf "\nACRNAME=$ACRNAME"
printf "\nAKSCLUSTER=$AKSCLUSTER"
printf "\nRESOURCEGROUP=$RESOURCEGROUP"
printf "\nNODERESOURCEGROUP=$NODERESOURCEGROUP"
printf "\nSTATIC_IP=$STATIC_IP"
printf "\nDNS_LABEL=$DNS_LABEL"

printf "\nREGISTRY_NAME=$REGISTRY_NAME"
printf "\nSOURCE_REGISTRY=$SOURCE_REGISTRY"
printf "\nCONTROLLER_IMAGE=$CONTROLLER_IMAGE"
printf "\nCONTROLLER_TAG=$CONTROLLER_TAG"
printf "\nPATCH_IMAGE=$PATCH_IMAGE"
printf "\nPATCH_TAG=$PATCH_TAG"
printf "\nDEFAULTBACKEND_IMAGE=$DEFAULTBACKEND_IMAGE"
printf "\nDEFAULTBACKEND_TAG=$DEFAULTBACKEND_TAG"