#!/bin/bash
# export ACRNAME=mobexcr
# export AKSCLUSTER=reports-aks
# export RESOURCEGROUP=reports
# export NODERESOURCEGROUP=MC_reports_reports-aks_centralus
printf "\nACRNAME=$ACRNAME"
printf "\nAKSCLUSTER=$AKSCLUSTER"
printf "\nRESOURCEGROUP=$RESOURCEGROUP"
printf "\nNODERESOURCEGROUP=$NODERESOURCEGROUP"
printf "\nSTATIC_IP=$STATIC_IP"
printf "\nPUBLICIPID=$PUBLICIPID"
printf "\nDNS_LABEL=$DNS_LABEL"

printf "\nREGISTRY_NAME=$REGISTRY_NAME"
printf "\nSOURCE_REGISTRY=$SOURCE_REGISTRY"
printf "\nCONTROLLER_IMAGE=$CONTROLLER_IMAGE"
printf "\nCONTROLLER_TAG=$CONTROLLER_TAG"
printf "\nPATCH_IMAGE=$PATCH_IMAGE"
printf "\nPATCH_TAG=$PATCH_TAG"
printf "\nDEFAULTBACKEND_IMAGE=$DEFAULTBACKEND_IMAGE"
printf "\nDEFAULTBACKEND_TAG=$DEFAULTBACKEND_TAG"


printf "\nREGISTRY_NAME=$REGISTRY_NAME"
printf "\nCERT_MANAGER_REGISTRY=$CERT_MANAGER_REGISTRY"
printf "\nCERT_MANAGER_TAG=$CERT_MANAGER_TAG"
printf "\nCERT_MANAGER_IMAGE_CONTROLLER=$CERT_MANAGER_IMAGE_CONTROLLER"
printf "\nCERT_MANAGER_IMAGE_WEBHOOK=$CERT_MANAGER_IMAGE_WEBHOOK"
printf "\nCERT_MANAGER_IMAGE_CAINJECTOR=$CERT_MANAGER_IMAGE_CAINJECTOR"
printf "\nACR_URL=$ACR_URL"
