apiVersion: v1
kind: Pod
metadata:
  name: cron-test
  namespace: default
spec:
  hostNetwork: true
  dnsPolicy: Default
  containers:
  - name: send-email
    image: brentgroves/cron-test:7
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  

