apiVersion: v1
kind: Pod
metadata:
  name: cron-hostnetwork-pod
  namespace: default
spec:
  hostNetwork: true
  dnsPolicy: Default
  containers:
  - name: cron-hostnetwork-pod
    image: brentgroves/cron-test:7
    command: ["/bin/sh"]
    args:
      - -c
      - >-
          cron start &&
          tail -f /var/log/cron.log
    # command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  

# cron start
    # command: ["/bin/sh"]
    # args: ["-c", "printenv; #OR WHATEVER COMMAND YOU WANT"]    
# command: ["/bin/sh","-c"]
# args: ["command one; command two && command three"]

    # command: ["/bin/sh"]
    # args:
    #   - -c
    #   - >-
    #       command1 arg1 arg2 &&
    #       command2 arg3 &&
    #       command3 arg4    
    # command: ["/bin/sleep", "3650d"]
