kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: busybox-jiva-pvc
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G