version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    - "443:443"
    restart: always
    depends_on:
    - hockeypuck
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    # https://linuxize.com/post/bash-wait/
    # reference process id
# $$ is used to reference process id of any command or bash script. $0. 
# $0 is used to get the name of the command in a bash script.
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    command: ["sh","nginxReloader.sh"]
    logging:
      options:
        max-size: "10m"
        max-file: "3"
