# addresspool.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: custom-addresspool
  namespace: metallb-system
spec: 
  addresses:
  - 10.1.0.110-10.1.0.112

# 10.1.0.110      reports11
# 10.1.0.111      reports12
# 10.1.0.112      reports13