---
apiVersion: v1
kind: Service
metadata:
  name: reports-mongodb-0
  namespace: mongo
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: reports-mongodb-0
  ports:
  - name: reports-mongodb-0
    protocol: TCP
    nodePort: 30351
    port: 27017
    targetPort: 27017 

