# https://github.com/balchua/do-microk8s/blob/master/docs/openebs.md
apiVersion: apps/v1
kind: Deployment
metadata:
 name: busybox-hostpath
 labels:
   app: busybox-hostpath
spec:
 replicas: 1
 strategy:
   type: RollingUpdate
 selector:
   matchLabels:
     app: busybox-hostpath
 template:
   metadata:
     labels:
       app: busybox-hostpath
   spec:
     containers:
     - resources:
          limits:
           cpu: 0.5
       name: busybox
       image: busybox
       command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
       imagePullPolicy: IfNotPresent
       ports:
        - containerPort: 3306
          name: busybox
       volumeMounts:
       - mountPath: /my-data
         name: busybox-hostpath-vol1
     volumes:
      - name: busybox-hostpath-vol1
        persistentVolumeClaim:
          claimName: busybox-hostpath-pvc




