---
- name: test
  hosts: localhost
  remote_user: brent

  tasks:
  - name: "example cronjob"
    ansible.builtin.cron:
      name: "add-test-2"
      state: present
      minute: "*/2"
      hour: "*"
      day: "*"
      month: "*"
      weekday: "*"
      job: 'logger "ansible-pilot-2"'
      