# addresspool.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: custom-addresspool
  namespace: metallb-system
spec: 
  addresses:
  - 172.20.88.61-172.20.88.63

# 172.20.88.61    reports31
# 172.20.88.62    reports32
# 172.20.88.63    reports33